<?php

/*********************************************************************
* Extension configuration file for ext "realurl".
*
* Generated by ext 25-11-2016 07:52 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'RealURL: speaking paths for TYPO3',
  'description' => 'WARNING! This version is obsolete and unsupported! It was not tested by the author and its work is not guaranteed! If you find bugs in this version, they will not be fixed! Use at your own risk. Last stable version of RealURL 1.x is 1.13.6. Users of TYPO3 7.6+ are strongly recommended to wait for upcoming RealURL version 2.',
  'category' => 'fe',
  'shy' => 0,
  'dependencies' => '',
  'conflicts' => 'cooluri,simulatestatic',
  'priority' => '',
  'loadOrder' => '',
  'module' => '',
  'state' => 'obsolete',
  'internal' => 0,
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => 'pages,sys_domain,pages_language_overlay,sys_template',
  'clearCacheOnLoad' => 1,
  'lockType' => '',
  'author' => 'Dmitry Dulepov',
  'author_email' => 'dmitry.dulepov@gmail.com',
  'author_company' => '',
  'CGLcompliance' => '',
  'CGLcompliance_note' => '',
  'version' => '1.13.7',
  '_md5_values_when_last_written' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'php' => '5.3.2-6.99.999',
      'typo3' => '4.5.40-7.6.999',
      'lowlevel' => '1.0.0-100.0.0',
    ),
    'conflicts' => 
    array (
      'cooluri' => '',
      'simulatestatic' => '',
    ),
    'suggests' => 
    array (
      'static_info_tables' => '2.0.2-',
    ),
  ),
  'suggests' => 
  array (
  ),
  'user' => 'dmitry',
  'comment' => 'WARNING: version 1.x is not supported anymore! Switch to 2.x now! // Two fixes in this upload: (1) compatibility TYPO3-CORE-SA-2016-022, (2) images do not show up in TYPO3 BE under 7.6.',
);

?>